//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabacr07.KanColleViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grabacr07.KanColleViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ※近日実装予定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Implement_Oncoming {
            get {
                return ResourceManager.GetString("Common_Implement_Oncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Notifications_Disable {
            get {
                return ResourceManager.GetString("Common_Notifications_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (未実装) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Notifications_NotImplemented {
            get {
                return ResourceManager.GetString("Common_Notifications_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Notifications_Title {
            get {
                return ResourceManager.GetString("Common_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Windows 8 以降) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Notifications_Windows8 {
            get {
                return ResourceManager.GetString("Common_Notifications_Windows8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ShipGirl {
            get {
                return ResourceManager.GetString("Common_ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧を生成しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonCatalog_GeneratingList {
            get {
                return ResourceManager.GetString("CommonCatalog_GeneratingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示の更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonCatalog_Refresh {
            get {
                return ResourceManager.GetString("CommonCatalog_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これはテスト通知です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug_NotificationMessage {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Debug_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Debug_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造ドック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard {
            get {
                return ResourceManager.GetString("Dockyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Complete {
            get {
                return ResourceManager.GetString("Dockyard_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造中の艦名をネタバレする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Display_Reveal {
            get {
                return ResourceManager.GetString("Dockyard_Display_Reveal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Display_Title {
            get {
                return ResourceManager.GetString("Dockyard_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Locked {
            get {
                return ResourceManager.GetString("Dockyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工廠第 {0} ドックでの{1}の建造が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Dockyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了時に通知を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドックごとに個別に設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Dockyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造中の艦 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_ShipName {
            get {
                return ResourceManager.GetString("Dockyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成時刻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_TimeComplete {
            get {
                return ResourceManager.GetString("Dockyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了まで に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Dockyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dockyard_Unused {
            get {
                return ResourceManager.GetString("Dockyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征に出ていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_NoExpedition {
            get {
                return ResourceManager.GetString("Expedition_NoExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」が遠征から帰投しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_NotificationMessage {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Expedition_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征帰投時に通知を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_Notifications_Enable {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Individual Fleet Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_Notifications_Individual {
            get {
                return ResourceManager.GetString("Expedition_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了時刻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_TimeComplete {
            get {
                return ResourceManager.GetString("Expedition_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊帰投まで に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制空戦力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_AirSuperiorityPotential {
            get {
                return ResourceManager.GetString("Fleets_AirSuperiorityPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平均 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Average {
            get {
                return ResourceManager.GetString("Fleets_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Level {
            get {
                return ResourceManager.GetString("Fleets_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速艦隊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Speed_Fast {
            get {
                return ResourceManager.GetString("Fleets_Speed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低速艦隊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Speed_Slow {
            get {
                return ResourceManager.GetString("Fleets_Speed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_Total {
            get {
                return ResourceManager.GetString("Fleets_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵能力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Fleets_ViewRange {
            get {
                return ResourceManager.GetString("Fleets_ViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   司令部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_FleetHQ {
            get {
                return ResourceManager.GetString("Homeport_FleetHQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改修資材: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_ImprovementMaterial {
            get {
                return ResourceManager.GetString("Homeport_ImprovementMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速建造材: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_InstantBuild {
            get {
                return ResourceManager.GetString("Homeport_InstantBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速修復材: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_InstantRepair {
            get {
                return ResourceManager.GetString("Homeport_InstantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保有装備: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_NoOfEquipment {
            get {
                return ResourceManager.GetString("Homeport_NoOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属艦娘: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Homeport_NoOfShips {
            get {
                return ResourceManager.GetString("Homeport_NoOfShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IntegratedView {
            get {
                return ResourceManager.GetString("IntegratedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この艦隊は遠征中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Expedition {
            get {
                return ResourceManager.GetString("MessageBar_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    完了時刻: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Expedition_TimeCompletion {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    帰投まで: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Expedition_TimeRemaining {
            get {
                return ResourceManager.GetString("MessageBar_Expedition_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に入渠中の艦娘がいます。 完了時刻: {0:MM/dd HH\:mm} 完了まで: {1}:{2:mm\:ss} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Repairing {
            get {
                return ResourceManager.GetString("MessageBar_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に入渠中の艦娘がいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_Repairing_Null {
            get {
                return ResourceManager.GetString("MessageBar_Repairing_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労中の艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_BadCondition {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_BadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に{0}がいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_CanNotReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanNotReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃可能！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_CanReSortie {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_CanReSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未補給の艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_LackForResources {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_LackForResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再出撃までの目安:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_Remaining {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_Separator {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中破以上の艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageBar_ReSortie_Wounded {
            get {
                return ResourceManager.GetString("MessageBar_ReSortie_Wounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} が大破しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notifications_CriticalCondition {
            get {
                return ResourceManager.GetString("Notifications_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大破警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notifications_CriticalCondition_Title {
            get {
                return ResourceManager.GetString("Notifications_CriticalCondition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労回復完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notifications_MoraleRestored {
            get {
                return ResourceManager.GetString("Notifications_MoraleRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」に編成されている艦娘の疲労が回復しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Notifications_MoraleRestored_Details {
            get {
                return ResourceManager.GetString("Notifications_MoraleRestored_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Overview_Data {
            get {
                return ResourceManager.GetString("Overview_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Overview_EquipmentList {
            get {
                return ResourceManager.GetString("Overview_EquipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦娘一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Overview_ShipList {
            get {
                return ResourceManager.GetString("Overview_ShipList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務画面の全ページにアクセスしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Detail_Untaken {
            get {
                return ResourceManager.GetString("Quest_Detail_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///    50 %  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Progress_50 {
            get {
                return ResourceManager.GetString("Quest_Progress_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///    80 %  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Progress_80 {
            get {
                return ResourceManager.GetString("Quest_Progress_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///    完了  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_State_Accomplished {
            get {
                return ResourceManager.GetString("Quest_State_Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (未取得の任務) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quest_Title_Untaken {
            get {
                return ResourceManager.GetString("Quest_Title_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在遂行中の任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_CurrentQuestList {
            get {
                return ResourceManager.GetString("Quests_CurrentQuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デイリー任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Daily {
            get {
                return ResourceManager.GetString("Quests_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マンスリー任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Monthly {
            get {
                return ResourceManager.GetString("Quests_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発生中の任務はありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_NoQuest {
            get {
                return ResourceManager.GetString("Quests_NoQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※進捗状況 (50 %, 80 %) はゲーム内の表示と同じです。敵艦隊の撃破数や遠征の成功回数のカウント等は行っていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Notice {
            get {
                return ResourceManager.GetString("Quests_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム内で [任務 (クエスト)] 画面を開いて、任務一覧を取得してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Untaken {
            get {
                return ResourceManager.GetString("Quests_Untaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィークリー任務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quests_Weekly {
            get {
                return ResourceManager.GetString("Quests_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大将 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Admiral {
            get {
                return ResourceManager.GetString("Rank_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大佐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中佐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Commander {
            get {
                return ResourceManager.GetString("Rank_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中堅少佐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   少佐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Lieutenant_Commander {
            get {
                return ResourceManager.GetString("Rank_Lieutenant_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元帥 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Marshal_Admiral {
            get {
                return ResourceManager.GetString("Rank_Marshal_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新米中佐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Novice_Commander {
            get {
                return ResourceManager.GetString("Rank_Novice_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新米少佐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Novice_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Novice_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   少将 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Rear_Admiral {
            get {
                return ResourceManager.GetString("Rank_Rear_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中将 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rank_Vice_Admiral {
            get {
                return ResourceManager.GetString("Rank_Vice_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠ドック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard {
            get {
                return ResourceManager.GetString("Repairyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_Locked {
            get {
                return ResourceManager.GetString("Repairyard_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠第 {0} ドックでの「{1}」の整備が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_NotificationMessage {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_NotificationMessage_Title {
            get {
                return ResourceManager.GetString("Repairyard_NotificationMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了時に通知を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_Notifications_Enable {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドックごとに個別に設定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_Notifications_Individual {
            get {
                return ResourceManager.GetString("Repairyard_Notifications_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠中の艦 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_ShipName {
            get {
                return ResourceManager.GetString("Repairyard_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完成時刻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_TimeComplete {
            get {
                return ResourceManager.GetString("Repairyard_TimeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整備完了まで に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Repairyard_TimeRemaining {
            get {
                return ResourceManager.GetString("Repairyard_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reparyard_Unused {
            get {
                return ResourceManager.GetString("Reparyard_Unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットの保存に失敗しました:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Screenshot_Failed {
            get {
                return ResourceManager.GetString("Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットを保存しました:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Screenshot_Saved {
            get {
                return ResourceManager.GetString("Screenshot_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム画面を  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Browser_ResetZoom_Pre {
            get {
                return ResourceManager.GetString("Settings_Browser_ResetZoom_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   % に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Browser_ResetZoom_Suf {
            get {
                return ResourceManager.GetString("Settings_Browser_ResetZoom_Suf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (誤ってズームしたとき用) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Browser_ResetZoomDescription {
            get {
                return ResourceManager.GetString("Settings_Browser_ResetZoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ上部のボタンでゲーム画面 (Internet Explorer) の表示サイズを変更できます。スクリーンショットは常に 100 % のサイズで撮影され、表示サイズ設定の影響を受けません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Browser_ZoomDescription {
            get {
                return ResourceManager.GetString("Settings_Browser_ZoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザー操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BrowserControl {
            get {
                return ResourceManager.GetString("Settings_BrowserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム倍率を 100 % に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BrowserControl_ClearZoomFactorButton {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_ClearZoomFactorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (表示) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BrowserControl_Display {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ゲームのページから移動します。ご注意ください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BrowserControl_Notice {
            get {
                return ResourceManager.GetString("Settings_BrowserControl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知音を設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CustomSound {
            get {
                return ResourceManager.GetString("Settings_CustomSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボリューム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CustomSound_Volume {
            get {
                return ResourceManager.GetString("Settings_CustomSound_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Display {
            get {
                return ResourceManager.GetString("Settings_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Flash {
            get {
                return ResourceManager.GetString("Settings_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This works with DMM.com. OSAPI, and API links now!
        ///[You must reload the game for the changes to take affect.] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Flash_Message {
            get {
                return ResourceManager.GetString("Settings_Flash_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Flash Quality: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Flash_Quality {
            get {
                return ResourceManager.GetString("Settings_Flash_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Best: Anti-Aliasing enabled on all images (Slowest)
        ///High: Default.
        ///Auto-High: Automatically lowers quality when needed.
        ///Medium: Average Performance
        ///AutoLow: Will emphasize speed when needed
        ///Low: Performance over quality. Ugliest setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Flash_Quality_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Flash_Quality_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Flash Window: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Flash_Window {
            get {
                return ResourceManager.GetString("Settings_Flash_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opaque: Default (Old IE has no HW accel)
        ///Direct: Fastest rendering speed (HW accel)
        ///GPU: Slow! GPU optimization for tablets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Flash_Window_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Flash_Window_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Logging {
            get {
                return ResourceManager.GetString("Settings_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドロップ・建造・開発ログを記録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Logging_Enable {
            get {
                return ResourceManager.GetString("Settings_Logging_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Network {
            get {
                return ResourceManager.GetString("Settings_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Password {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロキシ サーバーにユーザー名とパスワードが必要 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Required {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Network_Proxy_Auth_Username {
            get {
                return ResourceManager.GetString("Settings_Network_Proxy_Auth_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications {
            get {
                return ResourceManager.GetString("Settings_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のプラグインを使用して通知されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_ActiveNotificationPlugin {
            get {
                return ResourceManager.GetString("Settings_Notifications_ActiveNotificationPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知を早める： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_AheadOfTime {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦これ本体の仕様により、最大 1 分間短縮できます。サーバー時刻とのずれを加味し、40 ～ 50 秒に設定することを推奨します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_AheadOfTime_Description {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_AheadOfTime_Seconds {
            get {
                return ResourceManager.GetString("Settings_Notifications_AheadOfTime_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造完了時に通知する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_Construction_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Construction_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大破艦がいる場合に通知する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_CriticalCondition {
            get {
                return ResourceManager.GetString("Settings_Notifications_CriticalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征帰投時に通知する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_Expeditions_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Expeditions_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に編成されている艦娘の疲労が回復したら通知する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に編成されているすべて艦娘のコンディション値が上記の値以上になったときに通知されます。コンディション値は 3 分間で 3 ずつ回復しますが、KanColleViewer 実装の仕様により、通知タイミングは数秒 ～ 最大 3 分程度遅れる可能性があること予めご了承ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Description {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※[動作設定] &gt; [出撃コンディション] から設定できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Reference {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再出撃可能とするコンディション値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_FleetsMorale_Threshold {
            get {
                return ResourceManager.GetString("Settings_Notifications_FleetsMorale_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_NotificationPlugin {
            get {
                return ResourceManager.GetString("Settings_Notifications_NotificationPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠完了時に通知する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Notifications_Repair_Enabled {
            get {
                return ResourceManager.GetString("Settings_Notifications_Repair_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation {
            get {
                return ResourceManager.GetString("Settings_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦上偵察機 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_CarrierBasedRecon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_CarrierBasedRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   彩雲、二式艦上偵察機 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_CarrierBasedRecon_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_CarrierBasedRecon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (偵察機 × 2) + (電探) + √(装備込みの艦隊索敵値合計 - 偵察機 - 電探) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_New {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備による索敵値が重要とされる場合の計算方法 (推定) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_New_Desc {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_New_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   偵察機 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_Recon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水上爆撃機 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneBomber {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneBomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   瑞雲、瑞雲(六三四空)、試製晴嵐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneBomber_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneBomber_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水上偵察機 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneRecon {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   零式水上偵察機、零式水上観測機、九八式水上偵察機(夜偵) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_SeaplaneRecon_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_SeaplaneRecon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦娘と装備の索敵値の単純な合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_Simple {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KanColleViewer での従来の計算方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_Simple_Description {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Simple_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊の索敵値の算出に使用する計算式は、以下を使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoS_Title {
            get {
                return ResourceManager.GetString("Settings_Operation_LoS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵値計算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_LoSCalculation {
            get {
                return ResourceManager.GetString("Settings_Operation_LoSCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃コンディション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_SortieCondition {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※通常は、間宮アイコンが消灯する 40 か、自然回復上限の 49 に設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_SortieCondition_Description {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊内の全艦のコンディションが次の数値以上になったとき、出撃可能と判断する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Operation_SortieCondition_Title {
            get {
                return ResourceManager.GetString("Settings_Operation_SortieCondition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Other {
            get {
                return ResourceManager.GetString("Settings_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロキシ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy {
            get {
                return ResourceManager.GetString("Settings_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信にプロキシ サーバーを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Enable {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SSL 接続時もプロキシサーバーを使用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Enable_4_SSL {
            get {
                return ResourceManager.GetString("Settings_Proxy_Enable_4_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Host {
            get {
                return ResourceManager.GetString("Settings_Proxy_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Proxy_Port {
            get {
                return ResourceManager.GetString("Settings_Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot {
            get {
                return ResourceManager.GetString("Settings_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_OpenButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スクリーンショットの保存先を指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderSelectionDialog_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderSelectionDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先フォルダーのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_FolderTextBox_Prompt {
            get {
                return ResourceManager.GetString("Settings_Screenshot_FolderTextBox_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_ImageFormat_Label {
            get {
                return ResourceManager.GetString("Settings_Screenshot_ImageFormat_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Screenshot_OpenFolderButton {
            get {
                return ResourceManager.GetString("Settings_Screenshot_OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Translations {
            get {
                return ResourceManager.GetString("Settings_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Append untranslated items to the translation files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Translations_Add_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Add_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translate game items, ships, and quests to selected language? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Translations_Enable {
            get {
                return ResourceManager.GetString("Settings_Translations_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UI {
            get {
                return ResourceManager.GetString("Settings_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイコンを利用する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UI_Icon {
            get {
                return ResourceManager.GetString("Settings_UI_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時に言語ファイルをアップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_AutoUpdateTrans {
            get {
                return ResourceManager.GetString("Settings_Updates_AutoUpdateTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートの有無をチェックしています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_CheckUpdateButn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdateButn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_CheckUpdatesBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdatesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートがあるかどうかチェックします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_CheckUpdatesBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_CheckUpdatesBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_CurrentVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   強制的に更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_ForceUpdateTransBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_ForceUpdateTransBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新の有無に関係なくすべての言語ファイルをダウンロードします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_ForceUpdateTransBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_ForceUpdateTransBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配布サイトに行く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_GetKCVBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_GetKCVBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新版の配布サイトを開きます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_GetKCVBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_GetKCVBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_OnlineVersion {
            get {
                return ResourceManager.GetString("Settings_Updates_OnlineVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_Option {
            get {
                return ResourceManager.GetString("Settings_Updates_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時にアップデートチェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_UpdateOnStartup {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語ファイルをダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートがある場合は言語ファイルをダウンロードします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Updates_UpdateTransBtn_ToolTip {
            get {
                return ResourceManager.GetString("Settings_Updates_UpdateTransBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_VersionInfo {
            get {
                return ResourceManager.GetString("Settings_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Window {
            get {
                return ResourceManager.GetString("Settings_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウを常に最前面に表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Window_TopMost {
            get {
                return ResourceManager.GetString("Settings_Window_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowControl {
            get {
                return ResourceManager.GetString("Settings_WindowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウをモニターの左端に寄せる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 インチタブレット (800 x 1280) 用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowControl_LocationLeftButton_Sub {
            get {
                return ResourceManager.GetString("Settings_WindowControl_LocationLeftButton_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ship_RepairDockToolTip {
            get {
                return ResourceManager.GetString("Ship_RepairDockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   施設: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ship_RepairFacilityToolTip {
            get {
                return ResourceManager.GetString("Ship_RepairFacilityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ship_Repairing {
            get {
                return ResourceManager.GetString("Ship_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_All {
            get {
                return ResourceManager.GetString("ShipCatalog_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_AntiAir {
            get {
                return ResourceManager.GetString("ShipCatalog_AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対潜 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_AntiSub {
            get {
                return ResourceManager.GetString("ShipCatalog_AntiSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装甲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Armor {
            get {
                return ResourceManager.GetString("ShipCatalog_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Equips {
            get {
                return ResourceManager.GetString("ShipCatalog_Equips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回避 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Evasion {
            get {
                return ResourceManager.GetString("ShipCatalog_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征中の艦を除外する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_ExcludeShipOnExpedition {
            get {
                return ResourceManager.GetString("ShipCatalog_ExcludeShipOnExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦種を除く！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_ExcludeShiptype {
            get {
                return ResourceManager.GetString("ShipCatalog_ExcludeShiptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Expedition {
            get {
                return ResourceManager.GetString("ShipCatalog_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Fast {
            get {
                return ResourceManager.GetString("ShipCatalog_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルター設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_FilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_FilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Firepower {
            get {
                return ResourceManager.GetString("ShipCatalog_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Level {
            get {
                return ResourceManager.GetString("ShipCatalog_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv.1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Level1 {
            get {
                return ResourceManager.GetString("ShipCatalog_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lv.2 以上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Level2Up {
            get {
                return ResourceManager.GetString("ShipCatalog_Level2Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Lock {
            get {
                return ResourceManager.GetString("ShipCatalog_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックしている に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Locked {
            get {
                return ResourceManager.GetString("ShipCatalog_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_LoS {
            get {
                return ResourceManager.GetString("ShipCatalog_LoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Luck {
            get {
                return ResourceManager.GetString("ShipCatalog_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   近代化改修 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Modernization {
            get {
                return ResourceManager.GetString("ShipCatalog_Modernization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改修完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_ModernizationComplete {
            get {
                return ResourceManager.GetString("ShipCatalog_ModernizationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改修未完 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_ModernizationIncomplete {
            get {
                return ResourceManager.GetString("ShipCatalog_ModernizationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Name {
            get {
                return ResourceManager.GetString("ShipCatalog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AL 作戦参加済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Operation_AL {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MI 作戦参加済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Operation_MI {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作戦出撃なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Operation_NeitherALnorMI {
            get {
                return ResourceManager.GetString("ShipCatalog_Operation_NeitherALnorMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改造 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Remodel {
            get {
                return ResourceManager.GetString("ShipCatalog_Remodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改造完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_RemodelComplete {
            get {
                return ResourceManager.GetString("ShipCatalog_RemodelComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改造未完 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_RemodelIncomplete {
            get {
                return ResourceManager.GetString("ShipCatalog_RemodelIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルター設定リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_ResetFilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_ResetFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルター設定を保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_SaveFilterSettings {
            get {
                return ResourceManager.GetString("ShipCatalog_SaveFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_SelectAll {
            get {
                return ResourceManager.GetString("ShipCatalog_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_ShipType {
            get {
                return ResourceManager.GetString("ShipCatalog_ShipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータスをすべて表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_ShowAdditionalShipStats {
            get {
                return ResourceManager.GetString("ShipCatalog_ShowAdditionalShipStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Slow {
            get {
                return ResourceManager.GetString("ShipCatalog_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃海域 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_SortieWaters {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AL 作戦 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_SortieWaters_AL {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters_AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MI 作戦 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_SortieWaters_MI {
            get {
                return ResourceManager.GetString("ShipCatalog_SortieWaters_MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   速力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Speed {
            get {
                return ResourceManager.GetString("ShipCatalog_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   雷装 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Torpedo {
            get {
                return ResourceManager.GetString("ShipCatalog_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロックしていない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShipCatalog_Unlocked {
            get {
                return ResourceManager.GetString("ShipCatalog_Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工廠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard {
            get {
                return ResourceManager.GetString("Shipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建造 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard_ConstructionDock {
            get {
                return ResourceManager.GetString("Shipyard_ConstructionDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備開発・ドロップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard_Development {
            get {
                return ResourceManager.GetString("Shipyard_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard_Development_Result_Failure {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard_Development_Result_None {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard_Development_Result_Success {
            get {
                return ResourceManager.GetString("Shipyard_Development_Result_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドロップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard_Drop {
            get {
                return ResourceManager.GetString("Shipyard_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入渠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shipyard_RepairDock {
            get {
                return ResourceManager.GetString("Shipyard_RepairDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlotItemCatalog_EqipName {
            get {
                return ResourceManager.GetString("SlotItemCatalog_EqipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装備している艦娘 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlotItemCatalog_EquippedShipGirls {
            get {
                return ResourceManager.GetString("SlotItemCatalog_EquippedShipGirls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   余り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlotItemCatalog_Extra {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所持数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlotItemCatalog_Owned {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlotItemCatalog_Stats {
            get {
                return ResourceManager.GetString("SlotItemCatalog_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_ClearCacheButton {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュを削除しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_ClearCacheButtonMessage {
            get {
                return ResourceManager.GetString("StartContent_ClearCacheButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「提督業も忙しい！」は、艦これを遊びやすくするためのツールです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_Introduction1 {
            get {
                return ResourceManager.GetString("StartContent_Introduction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Cookie Region に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_SetRegionCookieButton {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cookie has been set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_SetRegionCookieMessage {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make sure DMM.com is set to Japanese (日本語) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_SetRegionCookieToolTip {
            get {
                return ResourceManager.GetString("StartContent_SetRegionCookieToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartContent_Welcom {
            get {
                return ResourceManager.GetString("StartContent_Welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大破した艦娘がいます！！！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_CriticalDamage {
            get {
                return ResourceManager.GetString("StateDetail_CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に艦娘が編成されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_EmptyFleet {
            get {
                return ResourceManager.GetString("StateDetail_EmptyFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出撃可能！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_IsReady {
            get {
                return ResourceManager.GetString("StateDetail_IsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労回復済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_MoraleRecovering {
            get {
                return ResourceManager.GetString("StateDetail_MoraleRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   疲労回復まで に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_MoraleRecoveryTimer {
            get {
                return ResourceManager.GetString("StateDetail_MoraleRecoveryTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遠征中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_OnExpedition {
            get {
                return ResourceManager.GetString("StateDetail_OnExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊は出撃中です！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_OnSortie {
            get {
                return ResourceManager.GetString("StateDetail_OnSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に入渠中の艦娘がいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_Repairing {
            get {
                return ResourceManager.GetString("StateDetail_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦隊に未補給の艦娘がいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StateDetail_ShortSupply {
            get {
                return ResourceManager.GetString("StateDetail_ShortSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   命中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Accuracy {
            get {
                return ResourceManager.GetString("Stats_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_AntiAir {
            get {
                return ResourceManager.GetString("Stats_AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対潜 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_AntiSub {
            get {
                return ResourceManager.GetString("Stats_AntiSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装甲 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Armor {
            get {
                return ResourceManager.GetString("Stats_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   射程 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_AttackRange {
            get {
                return ResourceManager.GetString("Stats_AttackRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   爆装 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_DiveBomb {
            get {
                return ResourceManager.GetString("Stats_DiveBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回避 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Evasion {
            get {
                return ResourceManager.GetString("Stats_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Firepower {
            get {
                return ResourceManager.GetString("Stats_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   耐久 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Health {
            get {
                return ResourceManager.GetString("Stats_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Luck {
            get {
                return ResourceManager.GetString("Stats_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索敵 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_SightRange {
            get {
                return ResourceManager.GetString("Stats_SightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   速力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Speed {
            get {
                return ResourceManager.GetString("Stats_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   雷装 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Stats_Torpedo {
            get {
                return ResourceManager.GetString("Stats_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   艦これの起動を待っています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusBar_NotStarted {
            get {
                return ResourceManager.GetString("StatusBar_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StatusBar_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートチェックに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Notification_CheckFailed {
            get {
                return ResourceManager.GetString("Updater_Notification_CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいバージョンがあります 「v{0}」
        ///ここをクリックするとサイトが開きます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Notification_NewAppVersion {
            get {
                return ResourceManager.GetString("Updater_Notification_NewAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Notification_Title {
            get {
                return ResourceManager.GetString("Updater_Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語ファイルのダウンロードに失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Notification_TransUpdate_Fail {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語ファイルは既に最新版です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Notification_TransUpdate_Same {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語ファイルをアップデートしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Updater_Notification_TransUpdate_Success {
            get {
                return ResourceManager.GetString("Updater_Notification_TransUpdate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム {0} % はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomAction_OutOfRange {
            get {
                return ResourceManager.GetString("ZoomAction_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズームに失敗しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomAction_ZoomFailed {
            get {
                return ResourceManager.GetString("ZoomAction_ZoomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム画面の表示サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomFactorSelector {
            get {
                return ResourceManager.GetString("ZoomFactorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム画面の表示サイズを調整 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZoomFactorSelector_Tooltip {
            get {
                return ResourceManager.GetString("ZoomFactorSelector_Tooltip", resourceCulture);
            }
        }
    }
}
